name = "astro-contact-worker"
main = "src/worker.ts"
compatibility_date = "2025-09-08"

[vars]
# Email provider API key injected via dashboard or wrangler secret
# POSTMARK_TOKEN / RESEND_TOKEN etc.
RATE_LIMIT_MAX = 5
RATE_LIMIT_WINDOW = 300

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "" # fill after creating KV namespace (wrangler kv:namespace create rate_limit)
